### ISSUE TITLE
Frame format MDP

### ISSUE THREAD

**Issue by error404-personnotfound** [servalproject/serval-dna#129] opened 2017-11-21 14:26 UTC
What are the fields ST, RB, 1H, Broadcast ID and Rx SID in MDP packet format. How are the values set and why is it 33 when the ip adress is only of 32 bits. 
![image](https://user-images.githubusercontent.com/30428236/33077521-0c684916-cef6-11e7-978b-9ea0fefc905e.png)

**Comment by nanometrenat** [comment] 2017-11-24 09:43
I believe this is a duplicate of https://github.com/servalproject/serval-docs/issues/4 (which has been resolved)

**Closed as completed** 2017-11-24 11:07 UTC
