### ISSUE TITLE
servald REST API doesn't show a listing of peers

### ISSUE THREAD

**Issue by TobiasWooldridge** [servalproject/serval-dna#83] opened 2014-09-01 05:35 UTC
At the moment the serval REST API doesn't implement a listing of peers on the mesh

I'd like to implement this

What should I use for the URL, and which fields should I include in the JSON?

Thanks!

**Comment by quixotique** [comment] 2016-02-17 21:44
Duplicate of #96

**Closed as completed by quixotique** 2016-02-17 21:44 UTC
